export const FETCH_CREATED_CAMPAIGNS = 'FETCH_CREATEDCAMPAIGNS'
export const FETCH_DONATED_CAMPAIGNS = 'FETCH_DONATEDCAMPAIGNS'
export const CREATED_CAMPAIGNS = 'CREATED_CAMPAIGNS'
export const DONATED_CAMPAIGNS = 'DONATED_CAMPAIGNS'
