export const FETCH_CREATEDCAMPAIGNS = 'FETCH_CREATEDCAMPAIGNS'
export const FETCH_DONATEDCAMPAIGNS = 'FETCH_DONATEDCAMPAIGNS'
export const CREATED_CAMPAIGNS = 'CREATED_CAMPAIGNS'
export const DONATED_CAMPAIGNS = 'DONATED_CAMPAIGNS'


